# Generated by Django 6.0.7 on 2026-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_genre_language_movie_genres_movie_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="catalog.actor"
            ),
        ),
    ]
