# Generated by Django 6.0.7 on 2026-08-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_actor_movie_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="actors/"),
        ),
    ]
